var Horaire00120191007Gestion3525 = { horaires:
          [ { typequart: 'Nuit',
              joursemaine: 'Mercredi',
              nomemploye: 'ELAINE R BECKER' },
            { typequart: 'Jour',
              joursemaine: 'Jeudi',
              nomemploye: 'JENISSA C NASHEL' },
            { typequart: 'Soir',
              joursemaine: 'Jeudi',
              nomemploye: 'MASCHEAL SLATTON' },
            { typequart: 'Nuit',
              joursemaine: 'Jeudi',
              nomemploye: 'DESRI M PURNELL' } ] }
var HoraireGenere00120191007Gestion3525 =  {horaires:
          [ { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'DPURN',
              joursemaine: '4',
              typequart: 'N',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'EBECK',
              joursemaine: '3',
              typequart: 'S',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'EBECK',
              joursemaine: '6',
              typequart: 'N',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'EBECK',
              joursemaine: '7',
              typequart: 'J',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'JNASH',
              joursemaine: '4',
              typequart: 'S',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'JNASH',
              joursemaine: '6',
              typequart: 'S',
              selection: '1' },
            { idtablehoraire: '001',
              dateparam: '2019-10-07',
              idemployeur: 'Gestion3525',
              idemploye: 'JNASH',
              joursemaine: '7',
              typequart: 'J',
              selection: '2' } ]
}

module.exports = {
Horaire00120191007Gestion3525,
HoraireGenere00120191007Gestion3525
}
